baseurl="git@github.com:Teaching-projects/SOE-ProgAlap1-HF-2020-" 
remotes=(
    "hegyhati" 
    "szakitom"
    "hbela"
    "farkas1070"
    "barnabasivan"
    "ujvarivera"
    "Teo2002"
    "krisztikelemen"
    "kebeleicsaba"
    "Fmiri08"
)
